// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MoneyExchange.proto

package com.bingo.server.msg;

public final class MoneyExchange {
  private MoneyExchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MoneyExchangeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.MoneyExchangeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 num = 1;</code>
     */
    int getNum();

    /**
     * <code>optional bool add = 2;</code>
     */
    boolean getAdd();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.MoneyExchangeRequest}
   */
  public  static final class MoneyExchangeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.MoneyExchangeRequest)
      MoneyExchangeRequestOrBuilder {
    // Use MoneyExchangeRequest.newBuilder() to construct.
    private MoneyExchangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoneyExchangeRequest() {
      num_ = 0;
      add_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MoneyExchangeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              num_ = input.readInt32();
              break;
            }
            case 16: {

              add_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.class, com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.Builder.class);
    }

    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>optional int32 num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int ADD_FIELD_NUMBER = 2;
    private boolean add_;
    /**
     * <code>optional bool add = 2;</code>
     */
    public boolean getAdd() {
      return add_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (num_ != 0) {
        output.writeInt32(1, num_);
      }
      if (add_ != false) {
        output.writeBool(2, add_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num_);
      }
      if (add_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, add_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest other = (com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest) obj;

      boolean result = true;
      result = result && (getNum()
          == other.getNum());
      result = result && (getAdd()
          == other.getAdd());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (37 * hash) + ADD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAdd());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.MoneyExchangeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.MoneyExchangeRequest)
        com.bingo.server.msg.MoneyExchange.MoneyExchangeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.class, com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.Builder.class);
      }

      // Construct using com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        num_ = 0;

        add_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeRequest_descriptor;
      }

      public com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest getDefaultInstanceForType() {
        return com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.getDefaultInstance();
      }

      public com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest build() {
        com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest buildPartial() {
        com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest result = new com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest(this);
        result.num_ = num_;
        result.add_ = add_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest) {
          return mergeFrom((com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest other) {
        if (other == com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest.getDefaultInstance()) return this;
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (other.getAdd() != false) {
          setAdd(other.getAdd());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int num_ ;
      /**
       * <code>optional int32 num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 1;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 1;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }

      private boolean add_ ;
      /**
       * <code>optional bool add = 2;</code>
       */
      public boolean getAdd() {
        return add_;
      }
      /**
       * <code>optional bool add = 2;</code>
       */
      public Builder setAdd(boolean value) {
        
        add_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool add = 2;</code>
       */
      public Builder clearAdd() {
        
        add_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.MoneyExchangeRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.MoneyExchangeRequest)
    private static final com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest();
    }

    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoneyExchangeRequest>
        PARSER = new com.google.protobuf.AbstractParser<MoneyExchangeRequest>() {
      public MoneyExchangeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MoneyExchangeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MoneyExchangeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoneyExchangeRequest> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.MoneyExchange.MoneyExchangeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MoneyExchangeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.MoneyExchangeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    int getErrorCode();

    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    boolean hasRoleData();
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    com.bingo.server.msg.Entity.RoleData getRoleData();
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    com.bingo.server.msg.Entity.RoleDataOrBuilder getRoleDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.MoneyExchangeResponse}
   */
  public  static final class MoneyExchangeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.MoneyExchangeResponse)
      MoneyExchangeResponseOrBuilder {
    // Use MoneyExchangeResponse.newBuilder() to construct.
    private MoneyExchangeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoneyExchangeResponse() {
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MoneyExchangeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.bingo.server.msg.Entity.RoleData.Builder subBuilder = null;
              if (roleData_ != null) {
                subBuilder = roleData_.toBuilder();
              }
              roleData_ = input.readMessage(com.bingo.server.msg.Entity.RoleData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(roleData_);
                roleData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.class, com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ROLEDATA_FIELD_NUMBER = 2;
    private com.bingo.server.msg.Entity.RoleData roleData_;
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    public boolean hasRoleData() {
      return roleData_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    public com.bingo.server.msg.Entity.RoleData getRoleData() {
      return roleData_ == null ? com.bingo.server.msg.Entity.RoleData.getDefaultInstance() : roleData_;
    }
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    public com.bingo.server.msg.Entity.RoleDataOrBuilder getRoleDataOrBuilder() {
      return getRoleData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      if (roleData_ != null) {
        output.writeMessage(2, getRoleData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (roleData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRoleData());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse other = (com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && (hasRoleData() == other.hasRoleData());
      if (hasRoleData()) {
        result = result && getRoleData()
            .equals(other.getRoleData());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      if (hasRoleData()) {
        hash = (37 * hash) + ROLEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getRoleData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.MoneyExchangeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.MoneyExchangeResponse)
        com.bingo.server.msg.MoneyExchange.MoneyExchangeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.class, com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.Builder.class);
      }

      // Construct using com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        if (roleDataBuilder_ == null) {
          roleData_ = null;
        } else {
          roleData_ = null;
          roleDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.MoneyExchange.internal_static_com_bingo_server_msg_MoneyExchangeResponse_descriptor;
      }

      public com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse getDefaultInstanceForType() {
        return com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.getDefaultInstance();
      }

      public com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse build() {
        com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse buildPartial() {
        com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse result = new com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse(this);
        result.errorCode_ = errorCode_;
        if (roleDataBuilder_ == null) {
          result.roleData_ = roleData_;
        } else {
          result.roleData_ = roleDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse) {
          return mergeFrom((com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse other) {
        if (other == com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasRoleData()) {
          mergeRoleData(other.getRoleData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.bingo.server.msg.Entity.RoleData roleData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.Entity.RoleData, com.bingo.server.msg.Entity.RoleData.Builder, com.bingo.server.msg.Entity.RoleDataOrBuilder> roleDataBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public boolean hasRoleData() {
        return roleDataBuilder_ != null || roleData_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public com.bingo.server.msg.Entity.RoleData getRoleData() {
        if (roleDataBuilder_ == null) {
          return roleData_ == null ? com.bingo.server.msg.Entity.RoleData.getDefaultInstance() : roleData_;
        } else {
          return roleDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder setRoleData(com.bingo.server.msg.Entity.RoleData value) {
        if (roleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          roleData_ = value;
          onChanged();
        } else {
          roleDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder setRoleData(
          com.bingo.server.msg.Entity.RoleData.Builder builderForValue) {
        if (roleDataBuilder_ == null) {
          roleData_ = builderForValue.build();
          onChanged();
        } else {
          roleDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder mergeRoleData(com.bingo.server.msg.Entity.RoleData value) {
        if (roleDataBuilder_ == null) {
          if (roleData_ != null) {
            roleData_ =
              com.bingo.server.msg.Entity.RoleData.newBuilder(roleData_).mergeFrom(value).buildPartial();
          } else {
            roleData_ = value;
          }
          onChanged();
        } else {
          roleDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder clearRoleData() {
        if (roleDataBuilder_ == null) {
          roleData_ = null;
          onChanged();
        } else {
          roleData_ = null;
          roleDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public com.bingo.server.msg.Entity.RoleData.Builder getRoleDataBuilder() {
        
        onChanged();
        return getRoleDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public com.bingo.server.msg.Entity.RoleDataOrBuilder getRoleDataOrBuilder() {
        if (roleDataBuilder_ != null) {
          return roleDataBuilder_.getMessageOrBuilder();
        } else {
          return roleData_ == null ?
              com.bingo.server.msg.Entity.RoleData.getDefaultInstance() : roleData_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.Entity.RoleData, com.bingo.server.msg.Entity.RoleData.Builder, com.bingo.server.msg.Entity.RoleDataOrBuilder> 
          getRoleDataFieldBuilder() {
        if (roleDataBuilder_ == null) {
          roleDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.Entity.RoleData, com.bingo.server.msg.Entity.RoleData.Builder, com.bingo.server.msg.Entity.RoleDataOrBuilder>(
                  getRoleData(),
                  getParentForChildren(),
                  isClean());
          roleData_ = null;
        }
        return roleDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.MoneyExchangeResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.MoneyExchangeResponse)
    private static final com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse();
    }

    public static com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoneyExchangeResponse>
        PARSER = new com.google.protobuf.AbstractParser<MoneyExchangeResponse>() {
      public MoneyExchangeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MoneyExchangeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MoneyExchangeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoneyExchangeResponse> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.MoneyExchange.MoneyExchangeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_MoneyExchangeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_MoneyExchangeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_MoneyExchangeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_MoneyExchangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MoneyExchange.proto\022\024com.bingo.server." +
      "msg\032\014Entity.proto\"0\n\024MoneyExchangeReques" +
      "t\022\013\n\003num\030\001 \001(\005\022\013\n\003add\030\002 \001(\010\"\\\n\025MoneyExch" +
      "angeResponse\022\021\n\terrorCode\030\001 \001(\005\0220\n\010roleD" +
      "ata\030\002 \001(\0132\036.com.bingo.server.msg.RoleDat" +
      "ab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bingo.server.msg.Entity.getDescriptor(),
        }, assigner);
    internal_static_com_bingo_server_msg_MoneyExchangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bingo_server_msg_MoneyExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_MoneyExchangeRequest_descriptor,
        new java.lang.String[] { "Num", "Add", });
    internal_static_com_bingo_server_msg_MoneyExchangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bingo_server_msg_MoneyExchangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_MoneyExchangeResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "RoleData", });
    com.bingo.server.msg.Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
