// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG

package com.bingo.server.msg;

public final class MSG {
  private MSG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 每个消息定义一个消息Code
   * </pre>
   *
   * Protobuf enum {@code com.bingo.server.msg.MsgCode}
   */
  public enum MsgCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 基础消息,非应用层消息
     * </pre>
     *
     * <code>No_Support_Msg = 0;</code>
     */
    No_Support_Msg(0),
    /**
     * <pre>
     * 通讯层心跳请求
     * </pre>
     *
     * <code>Heart_Beat_Request = 1;</code>
     */
    Heart_Beat_Request(1),
    /**
     * <pre>
     * 通讯层心跳返回
     * </pre>
     *
     * <code>Heart_Beat_Response = 2;</code>
     */
    Heart_Beat_Response(2),
    /**
     * <pre>
     * 请求消息
     * </pre>
     *
     * <code>Weixin_Login_Request = 10013;</code>
     */
    Weixin_Login_Request(10013),
    /**
     * <pre>
     * 用户名密码注册, 暂时不使用
     * </pre>
     *
     * <code>Registry_Request = 10011;</code>
     */
    Registry_Request(10011),
    /**
     * <pre>
     * 用户名密码登录, 暂时不使用
     * </pre>
     *
     * <code>Login_Request = 10001;</code>
     */
    Login_Request(10001),
    /**
     * <pre>
     * 登出,无消息体
     * </pre>
     *
     * <code>Logout_Request = 10003;</code>
     */
    Logout_Request(10003),
    /**
     * <pre>
     * 获取最新版本信息, 无消息体
     * </pre>
     *
     * <code>Lastest_Version_Request = 10020;</code>
     */
    Lastest_Version_Request(10020),
    /**
     * <pre>
     * 获取最新的服务器时间戳, 无消息体
     * </pre>
     *
     * <code>Timestamp_Request = 10022;</code>
     */
    Timestamp_Request(10022),
    /**
     * <pre>
     * 获取用户信息, 无消息体
     * </pre>
     *
     * <code>Get_User_Info_Request = 10024;</code>
     */
    Get_User_Info_Request(10024),
    /**
     * <pre>
     * 获取手机验证码, 未使用
     * </pre>
     *
     * <code>Get_Validate_Code_Request = 10026;</code>
     */
    Get_Validate_Code_Request(10026),
    /**
     * <pre>
     * 绑定手机号, 未使用
     * </pre>
     *
     * <code>Bind_Phone_Request = 10027;</code>
     */
    Bind_Phone_Request(10027),
    /**
     * <pre>
     * 获取广播大厅广播消息, 无消息体
     * </pre>
     *
     * <code>Get_Broadcast_Request = 10029;</code>
     */
    Get_Broadcast_Request(10029),
    /**
     * <pre>
     * 获取用户消息中心消息,无消息体
     * </pre>
     *
     * <code>Get_Message_Request = 10031;</code>
     */
    Get_Message_Request(10031),
    /**
     * <pre>
     * 游戏消息
     * </pre>
     *
     * <code>Ddz_Get_Rule_Request = 51001;</code>
     */
    Ddz_Get_Rule_Request(51001),
    /**
     * <code>Ddz_New_Desk_Request = 50001;</code>
     */
    Ddz_New_Desk_Request(50001),
    /**
     * <pre>
     * 确认规则,开桌,无消息体
     * </pre>
     *
     * <code>Ddz_Check_In_Desk_Request = 50007;</code>
     */
    Ddz_Check_In_Desk_Request(50007),
    /**
     * <pre>
     * 确认规则,开桌
     * </pre>
     *
     * <code>Ddz_Confirm_Rule_Request = 50005;</code>
     */
    Ddz_Confirm_Rule_Request(50005),
    /**
     * <pre>
     * 获取用户好友列表, 无消息体
     * </pre>
     *
     * <code>Get_Friends_Request = 50009;</code>
     */
    Get_Friends_Request(50009),
    /**
     * <pre>
     * 进入牌桌
     * </pre>
     *
     * <code>Enter_Desk_Request = 50011;</code>
     */
    Enter_Desk_Request(50011),
    /**
     * <pre>
     * 重连牌桌
     * </pre>
     *
     * <code>Reconnect_Desk_Request = 50013;</code>
     */
    Reconnect_Desk_Request(50013),
    /**
     * <pre>
     * 准备
     * </pre>
     *
     * <code>Ddz_Ready_Request = 50015;</code>
     */
    Ddz_Ready_Request(50015),
    /**
     * <pre>
     * 叫地主
     * </pre>
     *
     * <code>Ddz_Call_Lord_Request = 50017;</code>
     */
    Ddz_Call_Lord_Request(50017),
    /**
     * <pre>
     * 出牌
     * </pre>
     *
     * <code>Ddz_Play_Card_Request = 50018;</code>
     */
    Ddz_Play_Card_Request(50018),
    /**
     * <pre>
     * 返回消息
     * </pre>
     *
     * <code>Success_Response = 10;</code>
     */
    Success_Response(10),
    /**
     * <pre>
     * 微信登录返回
     * </pre>
     *
     * <code>Weixin_Login_Response = 10014;</code>
     */
    Weixin_Login_Response(10014),
    /**
     * <pre>
     * 用户名密码注册返回, 暂时不使用
     * </pre>
     *
     * <code>Registry_Response = 10012;</code>
     */
    Registry_Response(10012),
    /**
     * <pre>
     * 用户名密码登录, 暂时不使用
     * </pre>
     *
     * <code>Login_Response = 10002;</code>
     */
    Login_Response(10002),
    /**
     * <pre>
     * 登出返回, 无消息体
     * </pre>
     *
     * <code>Logout_Response = 10004;</code>
     */
    Logout_Response(10004),
    /**
     * <pre>
     * 获取最新版本返回消息
     * </pre>
     *
     * <code>Lastest_Version_Response = 10021;</code>
     */
    Lastest_Version_Response(10021),
    /**
     * <pre>
     * 获取最新服务器时间戳
     * </pre>
     *
     * <code>Timestamp_Response = 10023;</code>
     */
    Timestamp_Response(10023),
    /**
     * <pre>
     * 获取用户信息返回
     * </pre>
     *
     * <code>Get_User_Info_Response = 10025;</code>
     */
    Get_User_Info_Response(10025),
    /**
     * <pre>
     * 绑定手机号成功返回, 无消息体, 未使用
     * </pre>
     *
     * <code>Bind_Phone_Response = 10028;</code>
     */
    Bind_Phone_Response(10028),
    /**
     * <pre>
     * 获取大厅广播消息
     * </pre>
     *
     * <code>Get_Broadcast_Response = 10030;</code>
     */
    Get_Broadcast_Response(10030),
    /**
     * <pre>
     * 返回消息内容
     * </pre>
     *
     * <code>Get_Message_Response = 10032;</code>
     */
    Get_Message_Response(10032),
    /**
     * <pre>
     * 获取斗地主可用规则选项
     * </pre>
     *
     * <code>Ddz_Get_Rule_Response = 50033;</code>
     */
    Ddz_Get_Rule_Response(50033),
    /**
     * <pre>
     * 确认规则,开桌
     * </pre>
     *
     * <code>Ddz_Check_In_Desk_Response = 50008;</code>
     */
    Ddz_Check_In_Desk_Response(50008),
    /**
     * <pre>
     * 确认规则,开桌返回
     * </pre>
     *
     * <code>Ddz_Confirm_Rule_Response = 50006;</code>
     */
    Ddz_Confirm_Rule_Response(50006),
    /**
     * <pre>
     * 获取用户好友列表返回
     * </pre>
     *
     * <code>Get_Friends_Response = 50010;</code>
     */
    Get_Friends_Response(50010),
    /**
     * <pre>
     * 进入牌桌返回
     * </pre>
     *
     * <code>Enter_Desk_Response = 50012;</code>
     */
    Enter_Desk_Response(50012),
    /**
     * <pre>
     * 重连牌桌返回
     * </pre>
     *
     * <code>Reconnect_Desk_Response = 50014;</code>
     */
    Reconnect_Desk_Response(50014),
    /**
     * <pre>
     * 斗地主准备返回
     * </pre>
     *
     * <code>Ddz_Ready_Response = 50016;</code>
     */
    Ddz_Ready_Response(50016),
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>On_Connect_Notification = 11;</code>
     */
    On_Connect_Notification(11),
    /**
     * <pre>
     * 游戏通知
     * </pre>
     *
     * <code>Ddz_New_Desk_Notification = 50002;</code>
     */
    Ddz_New_Desk_Notification(50002),
    /**
     * <code>Ddz_Enter_Desk_Notification = 50003;</code>
     */
    Ddz_Enter_Desk_Notification(50003),
    /**
     * <code>Ddz_Error_Notification = 50004;</code>
     */
    Ddz_Error_Notification(50004),
    /**
     * <pre>
     * 通知其他用户牌桌状态
     * </pre>
     *
     * <code>Ddz_Desk_Status_Notification = 50020;</code>
     */
    Ddz_Desk_Status_Notification(50020),
    /**
     * <pre>
     * 发牌通知消息
     * </pre>
     *
     * <code>Ddz_User_Notification = 50021;</code>
     */
    Ddz_User_Notification(50021),
    /**
     * <pre>
     * TODO 开桌,发牌,叫地主通知消息分开发送
     * </pre>
     *
     * <code>Ddz_Play_Card_Notification = 50019;</code>
     */
    Ddz_Play_Card_Notification(50019),
    /**
     * <pre>
     * 错误消息
     * </pre>
     *
     * <code>SYSTEM_ERROR = 9999;</code>
     */
    SYSTEM_ERROR(9999),
    /**
     * <code>BUSINESS_ERROR = 9998;</code>
     */
    BUSINESS_ERROR(9998),
    /**
     * <code>NOT_ONLINE_ERROR = 9997;</code>
     */
    NOT_ONLINE_ERROR(9997),
    /**
     * <code>NOT_CONNECT_ERROR = 9996;</code>
     */
    NOT_CONNECT_ERROR(9996),
    /**
     * <code>ACCOUNT_DISABLE_ERROR = 9995;</code>
     */
    ACCOUNT_DISABLE_ERROR(9995),
    /**
     * <code>NO_VERSION_ERROR = 9994;</code>
     */
    NO_VERSION_ERROR(9994),
    /**
     * <code>USER_NOT_EXIST_ERROR = 9993;</code>
     */
    USER_NOT_EXIST_ERROR(9993),
    /**
     * <code>WALLET_NOT_EXIST_ERROR = 9992;</code>
     */
    WALLET_NOT_EXIST_ERROR(9992),
    /**
     * <code>PHONE_CODE_VALIDATE_ERROR = 9991;</code>
     */
    PHONE_CODE_VALIDATE_ERROR(9991),
    /**
     * <pre>
     * 游戏错误
     * </pre>
     *
     * <code>DDZ_SYSTEM_ERROR = 55555;</code>
     */
    DDZ_SYSTEM_ERROR(55555),
    /**
     * <code>DDZ_BUSINESS_ERROR = 55554;</code>
     */
    DDZ_BUSINESS_ERROR(55554),
    /**
     * <pre>
     * LandLord Message
     * </pre>
     *
     * <code>Landlord_CS = 6001;</code>
     */
    Landlord_CS(6001),
    /**
     * <code>Landlord_SC = 6002;</code>
     */
    Landlord_SC(6002),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 基础消息,非应用层消息
     * </pre>
     *
     * <code>No_Support_Msg = 0;</code>
     */
    public static final int No_Support_Msg_VALUE = 0;
    /**
     * <pre>
     * 通讯层心跳请求
     * </pre>
     *
     * <code>Heart_Beat_Request = 1;</code>
     */
    public static final int Heart_Beat_Request_VALUE = 1;
    /**
     * <pre>
     * 通讯层心跳返回
     * </pre>
     *
     * <code>Heart_Beat_Response = 2;</code>
     */
    public static final int Heart_Beat_Response_VALUE = 2;
    /**
     * <pre>
     * 请求消息
     * </pre>
     *
     * <code>Weixin_Login_Request = 10013;</code>
     */
    public static final int Weixin_Login_Request_VALUE = 10013;
    /**
     * <pre>
     * 用户名密码注册, 暂时不使用
     * </pre>
     *
     * <code>Registry_Request = 10011;</code>
     */
    public static final int Registry_Request_VALUE = 10011;
    /**
     * <pre>
     * 用户名密码登录, 暂时不使用
     * </pre>
     *
     * <code>Login_Request = 10001;</code>
     */
    public static final int Login_Request_VALUE = 10001;
    /**
     * <pre>
     * 登出,无消息体
     * </pre>
     *
     * <code>Logout_Request = 10003;</code>
     */
    public static final int Logout_Request_VALUE = 10003;
    /**
     * <pre>
     * 获取最新版本信息, 无消息体
     * </pre>
     *
     * <code>Lastest_Version_Request = 10020;</code>
     */
    public static final int Lastest_Version_Request_VALUE = 10020;
    /**
     * <pre>
     * 获取最新的服务器时间戳, 无消息体
     * </pre>
     *
     * <code>Timestamp_Request = 10022;</code>
     */
    public static final int Timestamp_Request_VALUE = 10022;
    /**
     * <pre>
     * 获取用户信息, 无消息体
     * </pre>
     *
     * <code>Get_User_Info_Request = 10024;</code>
     */
    public static final int Get_User_Info_Request_VALUE = 10024;
    /**
     * <pre>
     * 获取手机验证码, 未使用
     * </pre>
     *
     * <code>Get_Validate_Code_Request = 10026;</code>
     */
    public static final int Get_Validate_Code_Request_VALUE = 10026;
    /**
     * <pre>
     * 绑定手机号, 未使用
     * </pre>
     *
     * <code>Bind_Phone_Request = 10027;</code>
     */
    public static final int Bind_Phone_Request_VALUE = 10027;
    /**
     * <pre>
     * 获取广播大厅广播消息, 无消息体
     * </pre>
     *
     * <code>Get_Broadcast_Request = 10029;</code>
     */
    public static final int Get_Broadcast_Request_VALUE = 10029;
    /**
     * <pre>
     * 获取用户消息中心消息,无消息体
     * </pre>
     *
     * <code>Get_Message_Request = 10031;</code>
     */
    public static final int Get_Message_Request_VALUE = 10031;
    /**
     * <pre>
     * 游戏消息
     * </pre>
     *
     * <code>Ddz_Get_Rule_Request = 51001;</code>
     */
    public static final int Ddz_Get_Rule_Request_VALUE = 51001;
    /**
     * <code>Ddz_New_Desk_Request = 50001;</code>
     */
    public static final int Ddz_New_Desk_Request_VALUE = 50001;
    /**
     * <pre>
     * 确认规则,开桌,无消息体
     * </pre>
     *
     * <code>Ddz_Check_In_Desk_Request = 50007;</code>
     */
    public static final int Ddz_Check_In_Desk_Request_VALUE = 50007;
    /**
     * <pre>
     * 确认规则,开桌
     * </pre>
     *
     * <code>Ddz_Confirm_Rule_Request = 50005;</code>
     */
    public static final int Ddz_Confirm_Rule_Request_VALUE = 50005;
    /**
     * <pre>
     * 获取用户好友列表, 无消息体
     * </pre>
     *
     * <code>Get_Friends_Request = 50009;</code>
     */
    public static final int Get_Friends_Request_VALUE = 50009;
    /**
     * <pre>
     * 进入牌桌
     * </pre>
     *
     * <code>Enter_Desk_Request = 50011;</code>
     */
    public static final int Enter_Desk_Request_VALUE = 50011;
    /**
     * <pre>
     * 重连牌桌
     * </pre>
     *
     * <code>Reconnect_Desk_Request = 50013;</code>
     */
    public static final int Reconnect_Desk_Request_VALUE = 50013;
    /**
     * <pre>
     * 准备
     * </pre>
     *
     * <code>Ddz_Ready_Request = 50015;</code>
     */
    public static final int Ddz_Ready_Request_VALUE = 50015;
    /**
     * <pre>
     * 叫地主
     * </pre>
     *
     * <code>Ddz_Call_Lord_Request = 50017;</code>
     */
    public static final int Ddz_Call_Lord_Request_VALUE = 50017;
    /**
     * <pre>
     * 出牌
     * </pre>
     *
     * <code>Ddz_Play_Card_Request = 50018;</code>
     */
    public static final int Ddz_Play_Card_Request_VALUE = 50018;
    /**
     * <pre>
     * 返回消息
     * </pre>
     *
     * <code>Success_Response = 10;</code>
     */
    public static final int Success_Response_VALUE = 10;
    /**
     * <pre>
     * 微信登录返回
     * </pre>
     *
     * <code>Weixin_Login_Response = 10014;</code>
     */
    public static final int Weixin_Login_Response_VALUE = 10014;
    /**
     * <pre>
     * 用户名密码注册返回, 暂时不使用
     * </pre>
     *
     * <code>Registry_Response = 10012;</code>
     */
    public static final int Registry_Response_VALUE = 10012;
    /**
     * <pre>
     * 用户名密码登录, 暂时不使用
     * </pre>
     *
     * <code>Login_Response = 10002;</code>
     */
    public static final int Login_Response_VALUE = 10002;
    /**
     * <pre>
     * 登出返回, 无消息体
     * </pre>
     *
     * <code>Logout_Response = 10004;</code>
     */
    public static final int Logout_Response_VALUE = 10004;
    /**
     * <pre>
     * 获取最新版本返回消息
     * </pre>
     *
     * <code>Lastest_Version_Response = 10021;</code>
     */
    public static final int Lastest_Version_Response_VALUE = 10021;
    /**
     * <pre>
     * 获取最新服务器时间戳
     * </pre>
     *
     * <code>Timestamp_Response = 10023;</code>
     */
    public static final int Timestamp_Response_VALUE = 10023;
    /**
     * <pre>
     * 获取用户信息返回
     * </pre>
     *
     * <code>Get_User_Info_Response = 10025;</code>
     */
    public static final int Get_User_Info_Response_VALUE = 10025;
    /**
     * <pre>
     * 绑定手机号成功返回, 无消息体, 未使用
     * </pre>
     *
     * <code>Bind_Phone_Response = 10028;</code>
     */
    public static final int Bind_Phone_Response_VALUE = 10028;
    /**
     * <pre>
     * 获取大厅广播消息
     * </pre>
     *
     * <code>Get_Broadcast_Response = 10030;</code>
     */
    public static final int Get_Broadcast_Response_VALUE = 10030;
    /**
     * <pre>
     * 返回消息内容
     * </pre>
     *
     * <code>Get_Message_Response = 10032;</code>
     */
    public static final int Get_Message_Response_VALUE = 10032;
    /**
     * <pre>
     * 获取斗地主可用规则选项
     * </pre>
     *
     * <code>Ddz_Get_Rule_Response = 50033;</code>
     */
    public static final int Ddz_Get_Rule_Response_VALUE = 50033;
    /**
     * <pre>
     * 确认规则,开桌
     * </pre>
     *
     * <code>Ddz_Check_In_Desk_Response = 50008;</code>
     */
    public static final int Ddz_Check_In_Desk_Response_VALUE = 50008;
    /**
     * <pre>
     * 确认规则,开桌返回
     * </pre>
     *
     * <code>Ddz_Confirm_Rule_Response = 50006;</code>
     */
    public static final int Ddz_Confirm_Rule_Response_VALUE = 50006;
    /**
     * <pre>
     * 获取用户好友列表返回
     * </pre>
     *
     * <code>Get_Friends_Response = 50010;</code>
     */
    public static final int Get_Friends_Response_VALUE = 50010;
    /**
     * <pre>
     * 进入牌桌返回
     * </pre>
     *
     * <code>Enter_Desk_Response = 50012;</code>
     */
    public static final int Enter_Desk_Response_VALUE = 50012;
    /**
     * <pre>
     * 重连牌桌返回
     * </pre>
     *
     * <code>Reconnect_Desk_Response = 50014;</code>
     */
    public static final int Reconnect_Desk_Response_VALUE = 50014;
    /**
     * <pre>
     * 斗地主准备返回
     * </pre>
     *
     * <code>Ddz_Ready_Response = 50016;</code>
     */
    public static final int Ddz_Ready_Response_VALUE = 50016;
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>On_Connect_Notification = 11;</code>
     */
    public static final int On_Connect_Notification_VALUE = 11;
    /**
     * <pre>
     * 游戏通知
     * </pre>
     *
     * <code>Ddz_New_Desk_Notification = 50002;</code>
     */
    public static final int Ddz_New_Desk_Notification_VALUE = 50002;
    /**
     * <code>Ddz_Enter_Desk_Notification = 50003;</code>
     */
    public static final int Ddz_Enter_Desk_Notification_VALUE = 50003;
    /**
     * <code>Ddz_Error_Notification = 50004;</code>
     */
    public static final int Ddz_Error_Notification_VALUE = 50004;
    /**
     * <pre>
     * 通知其他用户牌桌状态
     * </pre>
     *
     * <code>Ddz_Desk_Status_Notification = 50020;</code>
     */
    public static final int Ddz_Desk_Status_Notification_VALUE = 50020;
    /**
     * <pre>
     * 发牌通知消息
     * </pre>
     *
     * <code>Ddz_User_Notification = 50021;</code>
     */
    public static final int Ddz_User_Notification_VALUE = 50021;
    /**
     * <pre>
     * TODO 开桌,发牌,叫地主通知消息分开发送
     * </pre>
     *
     * <code>Ddz_Play_Card_Notification = 50019;</code>
     */
    public static final int Ddz_Play_Card_Notification_VALUE = 50019;
    /**
     * <pre>
     * 错误消息
     * </pre>
     *
     * <code>SYSTEM_ERROR = 9999;</code>
     */
    public static final int SYSTEM_ERROR_VALUE = 9999;
    /**
     * <code>BUSINESS_ERROR = 9998;</code>
     */
    public static final int BUSINESS_ERROR_VALUE = 9998;
    /**
     * <code>NOT_ONLINE_ERROR = 9997;</code>
     */
    public static final int NOT_ONLINE_ERROR_VALUE = 9997;
    /**
     * <code>NOT_CONNECT_ERROR = 9996;</code>
     */
    public static final int NOT_CONNECT_ERROR_VALUE = 9996;
    /**
     * <code>ACCOUNT_DISABLE_ERROR = 9995;</code>
     */
    public static final int ACCOUNT_DISABLE_ERROR_VALUE = 9995;
    /**
     * <code>NO_VERSION_ERROR = 9994;</code>
     */
    public static final int NO_VERSION_ERROR_VALUE = 9994;
    /**
     * <code>USER_NOT_EXIST_ERROR = 9993;</code>
     */
    public static final int USER_NOT_EXIST_ERROR_VALUE = 9993;
    /**
     * <code>WALLET_NOT_EXIST_ERROR = 9992;</code>
     */
    public static final int WALLET_NOT_EXIST_ERROR_VALUE = 9992;
    /**
     * <code>PHONE_CODE_VALIDATE_ERROR = 9991;</code>
     */
    public static final int PHONE_CODE_VALIDATE_ERROR_VALUE = 9991;
    /**
     * <pre>
     * 游戏错误
     * </pre>
     *
     * <code>DDZ_SYSTEM_ERROR = 55555;</code>
     */
    public static final int DDZ_SYSTEM_ERROR_VALUE = 55555;
    /**
     * <code>DDZ_BUSINESS_ERROR = 55554;</code>
     */
    public static final int DDZ_BUSINESS_ERROR_VALUE = 55554;
    /**
     * <pre>
     * LandLord Message
     * </pre>
     *
     * <code>Landlord_CS = 6001;</code>
     */
    public static final int Landlord_CS_VALUE = 6001;
    /**
     * <code>Landlord_SC = 6002;</code>
     */
    public static final int Landlord_SC_VALUE = 6002;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCode valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCode forNumber(int value) {
      switch (value) {
        case 0: return No_Support_Msg;
        case 1: return Heart_Beat_Request;
        case 2: return Heart_Beat_Response;
        case 10013: return Weixin_Login_Request;
        case 10011: return Registry_Request;
        case 10001: return Login_Request;
        case 10003: return Logout_Request;
        case 10020: return Lastest_Version_Request;
        case 10022: return Timestamp_Request;
        case 10024: return Get_User_Info_Request;
        case 10026: return Get_Validate_Code_Request;
        case 10027: return Bind_Phone_Request;
        case 10029: return Get_Broadcast_Request;
        case 10031: return Get_Message_Request;
        case 51001: return Ddz_Get_Rule_Request;
        case 50001: return Ddz_New_Desk_Request;
        case 50007: return Ddz_Check_In_Desk_Request;
        case 50005: return Ddz_Confirm_Rule_Request;
        case 50009: return Get_Friends_Request;
        case 50011: return Enter_Desk_Request;
        case 50013: return Reconnect_Desk_Request;
        case 50015: return Ddz_Ready_Request;
        case 50017: return Ddz_Call_Lord_Request;
        case 50018: return Ddz_Play_Card_Request;
        case 10: return Success_Response;
        case 10014: return Weixin_Login_Response;
        case 10012: return Registry_Response;
        case 10002: return Login_Response;
        case 10004: return Logout_Response;
        case 10021: return Lastest_Version_Response;
        case 10023: return Timestamp_Response;
        case 10025: return Get_User_Info_Response;
        case 10028: return Bind_Phone_Response;
        case 10030: return Get_Broadcast_Response;
        case 10032: return Get_Message_Response;
        case 50033: return Ddz_Get_Rule_Response;
        case 50008: return Ddz_Check_In_Desk_Response;
        case 50006: return Ddz_Confirm_Rule_Response;
        case 50010: return Get_Friends_Response;
        case 50012: return Enter_Desk_Response;
        case 50014: return Reconnect_Desk_Response;
        case 50016: return Ddz_Ready_Response;
        case 11: return On_Connect_Notification;
        case 50002: return Ddz_New_Desk_Notification;
        case 50003: return Ddz_Enter_Desk_Notification;
        case 50004: return Ddz_Error_Notification;
        case 50020: return Ddz_Desk_Status_Notification;
        case 50021: return Ddz_User_Notification;
        case 50019: return Ddz_Play_Card_Notification;
        case 9999: return SYSTEM_ERROR;
        case 9998: return BUSINESS_ERROR;
        case 9997: return NOT_ONLINE_ERROR;
        case 9996: return NOT_CONNECT_ERROR;
        case 9995: return ACCOUNT_DISABLE_ERROR;
        case 9994: return NO_VERSION_ERROR;
        case 9993: return USER_NOT_EXIST_ERROR;
        case 9992: return WALLET_NOT_EXIST_ERROR;
        case 9991: return PHONE_CODE_VALIDATE_ERROR;
        case 55555: return DDZ_SYSTEM_ERROR;
        case 55554: return DDZ_BUSINESS_ERROR;
        case 6001: return Landlord_CS;
        case 6002: return Landlord_SC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
            public MsgCode findValueByNumber(int number) {
              return MsgCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bingo.server.msg.MSG.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgCode[] VALUES = values();

    public static MsgCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bingo.server.msg.MsgCode)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
     */
    int getMsgCodeValue();
    /**
     * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
     */
    com.bingo.server.msg.MSG.MsgCode getMsgCode();

    /**
     * <pre>
     *消息系列号，主要用于Request和Response，Response的值必须和Request相同，使得发送端可以进行事务匹配处理
     * </pre>
     *
     * <code>optional fixed64 sequence = 2;</code>
     */
    long getSequence();

    /**
     * <code>optional .com.bingo.server.msg.Request request = 4;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .com.bingo.server.msg.Request request = 4;</code>
     */
    com.bingo.server.msg.REQ.Request getRequest();
    /**
     * <code>optional .com.bingo.server.msg.Request request = 4;</code>
     */
    com.bingo.server.msg.REQ.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .com.bingo.server.msg.Response response = 5;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .com.bingo.server.msg.Response response = 5;</code>
     */
    com.bingo.server.msg.RESP.Response getResponse();
    /**
     * <code>optional .com.bingo.server.msg.Response response = 5;</code>
     */
    com.bingo.server.msg.RESP.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
     */
    boolean hasNotification();
    /**
     * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
     */
    com.bingo.server.msg.NOTIFY.Notification getNotification();
    /**
     * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
     */
    com.bingo.server.msg.NOTIFY.NotificationOrBuilder getNotificationOrBuilder();

    /**
     * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
     */
    boolean hasCs();
    /**
     * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
     */
    com.bingo.server.msg.ClientMessage.CS getCs();
    /**
     * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
     */
    com.bingo.server.msg.ClientMessage.CSOrBuilder getCsOrBuilder();

    /**
     * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
     */
    boolean hasSc();
    /**
     * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
     */
    com.bingo.server.msg.ServerMessage.SC getSc();
    /**
     * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
     */
    com.bingo.server.msg.ServerMessage.SCOrBuilder getScOrBuilder();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      msgCode_ = 0;
      sequence_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              msgCode_ = rawValue;
              break;
            }
            case 17: {

              sequence_ = input.readFixed64();
              break;
            }
            case 34: {
              com.bingo.server.msg.REQ.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.bingo.server.msg.REQ.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.bingo.server.msg.RESP.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.bingo.server.msg.RESP.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.bingo.server.msg.NOTIFY.Notification.Builder subBuilder = null;
              if (notification_ != null) {
                subBuilder = notification_.toBuilder();
              }
              notification_ = input.readMessage(com.bingo.server.msg.NOTIFY.Notification.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notification_);
                notification_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              com.bingo.server.msg.ClientMessage.CS.Builder subBuilder = null;
              if (cs_ != null) {
                subBuilder = cs_.toBuilder();
              }
              cs_ = input.readMessage(com.bingo.server.msg.ClientMessage.CS.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cs_);
                cs_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              com.bingo.server.msg.ServerMessage.SC.Builder subBuilder = null;
              if (sc_ != null) {
                subBuilder = sc_.toBuilder();
              }
              sc_ = input.readMessage(com.bingo.server.msg.ServerMessage.SC.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sc_);
                sc_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.MSG.internal_static_com_bingo_server_msg_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.MSG.internal_static_com_bingo_server_msg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.MSG.Message.class, com.bingo.server.msg.MSG.Message.Builder.class);
    }

    public static final int MSGCODE_FIELD_NUMBER = 1;
    private int msgCode_;
    /**
     * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
     */
    public int getMsgCodeValue() {
      return msgCode_;
    }
    /**
     * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
     */
    public com.bingo.server.msg.MSG.MsgCode getMsgCode() {
      com.bingo.server.msg.MSG.MsgCode result = com.bingo.server.msg.MSG.MsgCode.valueOf(msgCode_);
      return result == null ? com.bingo.server.msg.MSG.MsgCode.UNRECOGNIZED : result;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private long sequence_;
    /**
     * <pre>
     *消息系列号，主要用于Request和Response，Response的值必须和Request相同，使得发送端可以进行事务匹配处理
     * </pre>
     *
     * <code>optional fixed64 sequence = 2;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int REQUEST_FIELD_NUMBER = 4;
    private com.bingo.server.msg.REQ.Request request_;
    /**
     * <code>optional .com.bingo.server.msg.Request request = 4;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.Request request = 4;</code>
     */
    public com.bingo.server.msg.REQ.Request getRequest() {
      return request_ == null ? com.bingo.server.msg.REQ.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .com.bingo.server.msg.Request request = 4;</code>
     */
    public com.bingo.server.msg.REQ.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RESPONSE_FIELD_NUMBER = 5;
    private com.bingo.server.msg.RESP.Response response_;
    /**
     * <code>optional .com.bingo.server.msg.Response response = 5;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.Response response = 5;</code>
     */
    public com.bingo.server.msg.RESP.Response getResponse() {
      return response_ == null ? com.bingo.server.msg.RESP.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .com.bingo.server.msg.Response response = 5;</code>
     */
    public com.bingo.server.msg.RESP.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int NOTIFICATION_FIELD_NUMBER = 6;
    private com.bingo.server.msg.NOTIFY.Notification notification_;
    /**
     * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
     */
    public boolean hasNotification() {
      return notification_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
     */
    public com.bingo.server.msg.NOTIFY.Notification getNotification() {
      return notification_ == null ? com.bingo.server.msg.NOTIFY.Notification.getDefaultInstance() : notification_;
    }
    /**
     * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
     */
    public com.bingo.server.msg.NOTIFY.NotificationOrBuilder getNotificationOrBuilder() {
      return getNotification();
    }

    public static final int CS_FIELD_NUMBER = 7;
    private com.bingo.server.msg.ClientMessage.CS cs_;
    /**
     * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
     */
    public boolean hasCs() {
      return cs_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
     */
    public com.bingo.server.msg.ClientMessage.CS getCs() {
      return cs_ == null ? com.bingo.server.msg.ClientMessage.CS.getDefaultInstance() : cs_;
    }
    /**
     * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
     */
    public com.bingo.server.msg.ClientMessage.CSOrBuilder getCsOrBuilder() {
      return getCs();
    }

    public static final int SC_FIELD_NUMBER = 8;
    private com.bingo.server.msg.ServerMessage.SC sc_;
    /**
     * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
     */
    public boolean hasSc() {
      return sc_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
     */
    public com.bingo.server.msg.ServerMessage.SC getSc() {
      return sc_ == null ? com.bingo.server.msg.ServerMessage.SC.getDefaultInstance() : sc_;
    }
    /**
     * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
     */
    public com.bingo.server.msg.ServerMessage.SCOrBuilder getScOrBuilder() {
      return getSc();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCode_ != com.bingo.server.msg.MSG.MsgCode.No_Support_Msg.getNumber()) {
        output.writeEnum(1, msgCode_);
      }
      if (sequence_ != 0L) {
        output.writeFixed64(2, sequence_);
      }
      if (request_ != null) {
        output.writeMessage(4, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(5, getResponse());
      }
      if (notification_ != null) {
        output.writeMessage(6, getNotification());
      }
      if (cs_ != null) {
        output.writeMessage(7, getCs());
      }
      if (sc_ != null) {
        output.writeMessage(8, getSc());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCode_ != com.bingo.server.msg.MSG.MsgCode.No_Support_Msg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgCode_);
      }
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, sequence_);
      }
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getResponse());
      }
      if (notification_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getNotification());
      }
      if (cs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getCs());
      }
      if (sc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getSc());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.MSG.Message)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.MSG.Message other = (com.bingo.server.msg.MSG.Message) obj;

      boolean result = true;
      result = result && msgCode_ == other.msgCode_;
      result = result && (getSequence()
          == other.getSequence());
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && (hasNotification() == other.hasNotification());
      if (hasNotification()) {
        result = result && getNotification()
            .equals(other.getNotification());
      }
      result = result && (hasCs() == other.hasCs());
      if (hasCs()) {
        result = result && getCs()
            .equals(other.getCs());
      }
      result = result && (hasSc() == other.hasSc());
      if (hasSc()) {
        result = result && getSc()
            .equals(other.getSc());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MSGCODE_FIELD_NUMBER;
      hash = (53 * hash) + msgCode_;
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequence());
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (hasNotification()) {
        hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getNotification().hashCode();
      }
      if (hasCs()) {
        hash = (37 * hash) + CS_FIELD_NUMBER;
        hash = (53 * hash) + getCs().hashCode();
      }
      if (hasSc()) {
        hash = (37 * hash) + SC_FIELD_NUMBER;
        hash = (53 * hash) + getSc().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.MSG.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.MSG.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MSG.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.MSG.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.MSG.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.Message)
        com.bingo.server.msg.MSG.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.MSG.internal_static_com_bingo_server_msg_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.MSG.internal_static_com_bingo_server_msg_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.MSG.Message.class, com.bingo.server.msg.MSG.Message.Builder.class);
      }

      // Construct using com.bingo.server.msg.MSG.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCode_ = 0;

        sequence_ = 0L;

        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        if (notificationBuilder_ == null) {
          notification_ = null;
        } else {
          notification_ = null;
          notificationBuilder_ = null;
        }
        if (csBuilder_ == null) {
          cs_ = null;
        } else {
          cs_ = null;
          csBuilder_ = null;
        }
        if (scBuilder_ == null) {
          sc_ = null;
        } else {
          sc_ = null;
          scBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.MSG.internal_static_com_bingo_server_msg_Message_descriptor;
      }

      public com.bingo.server.msg.MSG.Message getDefaultInstanceForType() {
        return com.bingo.server.msg.MSG.Message.getDefaultInstance();
      }

      public com.bingo.server.msg.MSG.Message build() {
        com.bingo.server.msg.MSG.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.MSG.Message buildPartial() {
        com.bingo.server.msg.MSG.Message result = new com.bingo.server.msg.MSG.Message(this);
        result.msgCode_ = msgCode_;
        result.sequence_ = sequence_;
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (notificationBuilder_ == null) {
          result.notification_ = notification_;
        } else {
          result.notification_ = notificationBuilder_.build();
        }
        if (csBuilder_ == null) {
          result.cs_ = cs_;
        } else {
          result.cs_ = csBuilder_.build();
        }
        if (scBuilder_ == null) {
          result.sc_ = sc_;
        } else {
          result.sc_ = scBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.MSG.Message) {
          return mergeFrom((com.bingo.server.msg.MSG.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.MSG.Message other) {
        if (other == com.bingo.server.msg.MSG.Message.getDefaultInstance()) return this;
        if (other.msgCode_ != 0) {
          setMsgCodeValue(other.getMsgCodeValue());
        }
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasNotification()) {
          mergeNotification(other.getNotification());
        }
        if (other.hasCs()) {
          mergeCs(other.getCs());
        }
        if (other.hasSc()) {
          mergeSc(other.getSc());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.MSG.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.MSG.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgCode_ = 0;
      /**
       * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
       */
      public int getMsgCodeValue() {
        return msgCode_;
      }
      /**
       * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
       */
      public Builder setMsgCodeValue(int value) {
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
       */
      public com.bingo.server.msg.MSG.MsgCode getMsgCode() {
        com.bingo.server.msg.MSG.MsgCode result = com.bingo.server.msg.MSG.MsgCode.valueOf(msgCode_);
        return result == null ? com.bingo.server.msg.MSG.MsgCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
       */
      public Builder setMsgCode(com.bingo.server.msg.MSG.MsgCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.MsgCode msgCode = 1;</code>
       */
      public Builder clearMsgCode() {
        
        msgCode_ = 0;
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <pre>
       *消息系列号，主要用于Request和Response，Response的值必须和Request相同，使得发送端可以进行事务匹配处理
       * </pre>
       *
       * <code>optional fixed64 sequence = 2;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <pre>
       *消息系列号，主要用于Request和Response，Response的值必须和Request相同，使得发送端可以进行事务匹配处理
       * </pre>
       *
       * <code>optional fixed64 sequence = 2;</code>
       */
      public Builder setSequence(long value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息系列号，主要用于Request和Response，Response的值必须和Request相同，使得发送端可以进行事务匹配处理
       * </pre>
       *
       * <code>optional fixed64 sequence = 2;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private com.bingo.server.msg.REQ.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.REQ.Request, com.bingo.server.msg.REQ.Request.Builder, com.bingo.server.msg.REQ.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public com.bingo.server.msg.REQ.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.bingo.server.msg.REQ.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public Builder setRequest(com.bingo.server.msg.REQ.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public Builder setRequest(
          com.bingo.server.msg.REQ.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public Builder mergeRequest(com.bingo.server.msg.REQ.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.bingo.server.msg.REQ.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public com.bingo.server.msg.REQ.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      public com.bingo.server.msg.REQ.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.bingo.server.msg.REQ.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.Request request = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.REQ.Request, com.bingo.server.msg.REQ.Request.Builder, com.bingo.server.msg.REQ.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.REQ.Request, com.bingo.server.msg.REQ.Request.Builder, com.bingo.server.msg.REQ.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private com.bingo.server.msg.RESP.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.RESP.Response, com.bingo.server.msg.RESP.Response.Builder, com.bingo.server.msg.RESP.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public com.bingo.server.msg.RESP.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.bingo.server.msg.RESP.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public Builder setResponse(com.bingo.server.msg.RESP.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public Builder setResponse(
          com.bingo.server.msg.RESP.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public Builder mergeResponse(com.bingo.server.msg.RESP.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              com.bingo.server.msg.RESP.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public com.bingo.server.msg.RESP.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      public com.bingo.server.msg.RESP.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.bingo.server.msg.RESP.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.Response response = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.RESP.Response, com.bingo.server.msg.RESP.Response.Builder, com.bingo.server.msg.RESP.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.RESP.Response, com.bingo.server.msg.RESP.Response.Builder, com.bingo.server.msg.RESP.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private com.bingo.server.msg.NOTIFY.Notification notification_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.NOTIFY.Notification, com.bingo.server.msg.NOTIFY.Notification.Builder, com.bingo.server.msg.NOTIFY.NotificationOrBuilder> notificationBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public boolean hasNotification() {
        return notificationBuilder_ != null || notification_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public com.bingo.server.msg.NOTIFY.Notification getNotification() {
        if (notificationBuilder_ == null) {
          return notification_ == null ? com.bingo.server.msg.NOTIFY.Notification.getDefaultInstance() : notification_;
        } else {
          return notificationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public Builder setNotification(com.bingo.server.msg.NOTIFY.Notification value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notification_ = value;
          onChanged();
        } else {
          notificationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public Builder setNotification(
          com.bingo.server.msg.NOTIFY.Notification.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          notification_ = builderForValue.build();
          onChanged();
        } else {
          notificationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public Builder mergeNotification(com.bingo.server.msg.NOTIFY.Notification value) {
        if (notificationBuilder_ == null) {
          if (notification_ != null) {
            notification_ =
              com.bingo.server.msg.NOTIFY.Notification.newBuilder(notification_).mergeFrom(value).buildPartial();
          } else {
            notification_ = value;
          }
          onChanged();
        } else {
          notificationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public Builder clearNotification() {
        if (notificationBuilder_ == null) {
          notification_ = null;
          onChanged();
        } else {
          notification_ = null;
          notificationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public com.bingo.server.msg.NOTIFY.Notification.Builder getNotificationBuilder() {
        
        onChanged();
        return getNotificationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      public com.bingo.server.msg.NOTIFY.NotificationOrBuilder getNotificationOrBuilder() {
        if (notificationBuilder_ != null) {
          return notificationBuilder_.getMessageOrBuilder();
        } else {
          return notification_ == null ?
              com.bingo.server.msg.NOTIFY.Notification.getDefaultInstance() : notification_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.Notification notification = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.NOTIFY.Notification, com.bingo.server.msg.NOTIFY.Notification.Builder, com.bingo.server.msg.NOTIFY.NotificationOrBuilder> 
          getNotificationFieldBuilder() {
        if (notificationBuilder_ == null) {
          notificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.NOTIFY.Notification, com.bingo.server.msg.NOTIFY.Notification.Builder, com.bingo.server.msg.NOTIFY.NotificationOrBuilder>(
                  getNotification(),
                  getParentForChildren(),
                  isClean());
          notification_ = null;
        }
        return notificationBuilder_;
      }

      private com.bingo.server.msg.ClientMessage.CS cs_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.ClientMessage.CS, com.bingo.server.msg.ClientMessage.CS.Builder, com.bingo.server.msg.ClientMessage.CSOrBuilder> csBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public boolean hasCs() {
        return csBuilder_ != null || cs_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public com.bingo.server.msg.ClientMessage.CS getCs() {
        if (csBuilder_ == null) {
          return cs_ == null ? com.bingo.server.msg.ClientMessage.CS.getDefaultInstance() : cs_;
        } else {
          return csBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public Builder setCs(com.bingo.server.msg.ClientMessage.CS value) {
        if (csBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cs_ = value;
          onChanged();
        } else {
          csBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public Builder setCs(
          com.bingo.server.msg.ClientMessage.CS.Builder builderForValue) {
        if (csBuilder_ == null) {
          cs_ = builderForValue.build();
          onChanged();
        } else {
          csBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public Builder mergeCs(com.bingo.server.msg.ClientMessage.CS value) {
        if (csBuilder_ == null) {
          if (cs_ != null) {
            cs_ =
              com.bingo.server.msg.ClientMessage.CS.newBuilder(cs_).mergeFrom(value).buildPartial();
          } else {
            cs_ = value;
          }
          onChanged();
        } else {
          csBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public Builder clearCs() {
        if (csBuilder_ == null) {
          cs_ = null;
          onChanged();
        } else {
          cs_ = null;
          csBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public com.bingo.server.msg.ClientMessage.CS.Builder getCsBuilder() {
        
        onChanged();
        return getCsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      public com.bingo.server.msg.ClientMessage.CSOrBuilder getCsOrBuilder() {
        if (csBuilder_ != null) {
          return csBuilder_.getMessageOrBuilder();
        } else {
          return cs_ == null ?
              com.bingo.server.msg.ClientMessage.CS.getDefaultInstance() : cs_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.CS cs = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.ClientMessage.CS, com.bingo.server.msg.ClientMessage.CS.Builder, com.bingo.server.msg.ClientMessage.CSOrBuilder> 
          getCsFieldBuilder() {
        if (csBuilder_ == null) {
          csBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.ClientMessage.CS, com.bingo.server.msg.ClientMessage.CS.Builder, com.bingo.server.msg.ClientMessage.CSOrBuilder>(
                  getCs(),
                  getParentForChildren(),
                  isClean());
          cs_ = null;
        }
        return csBuilder_;
      }

      private com.bingo.server.msg.ServerMessage.SC sc_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.ServerMessage.SC, com.bingo.server.msg.ServerMessage.SC.Builder, com.bingo.server.msg.ServerMessage.SCOrBuilder> scBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public boolean hasSc() {
        return scBuilder_ != null || sc_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public com.bingo.server.msg.ServerMessage.SC getSc() {
        if (scBuilder_ == null) {
          return sc_ == null ? com.bingo.server.msg.ServerMessage.SC.getDefaultInstance() : sc_;
        } else {
          return scBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public Builder setSc(com.bingo.server.msg.ServerMessage.SC value) {
        if (scBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sc_ = value;
          onChanged();
        } else {
          scBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public Builder setSc(
          com.bingo.server.msg.ServerMessage.SC.Builder builderForValue) {
        if (scBuilder_ == null) {
          sc_ = builderForValue.build();
          onChanged();
        } else {
          scBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public Builder mergeSc(com.bingo.server.msg.ServerMessage.SC value) {
        if (scBuilder_ == null) {
          if (sc_ != null) {
            sc_ =
              com.bingo.server.msg.ServerMessage.SC.newBuilder(sc_).mergeFrom(value).buildPartial();
          } else {
            sc_ = value;
          }
          onChanged();
        } else {
          scBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public Builder clearSc() {
        if (scBuilder_ == null) {
          sc_ = null;
          onChanged();
        } else {
          sc_ = null;
          scBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public com.bingo.server.msg.ServerMessage.SC.Builder getScBuilder() {
        
        onChanged();
        return getScFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      public com.bingo.server.msg.ServerMessage.SCOrBuilder getScOrBuilder() {
        if (scBuilder_ != null) {
          return scBuilder_.getMessageOrBuilder();
        } else {
          return sc_ == null ?
              com.bingo.server.msg.ServerMessage.SC.getDefaultInstance() : sc_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.SC sc = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.ServerMessage.SC, com.bingo.server.msg.ServerMessage.SC.Builder, com.bingo.server.msg.ServerMessage.SCOrBuilder> 
          getScFieldBuilder() {
        if (scBuilder_ == null) {
          scBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.ServerMessage.SC, com.bingo.server.msg.ServerMessage.SC.Builder, com.bingo.server.msg.ServerMessage.SCOrBuilder>(
                  getSc(),
                  getParentForChildren(),
                  isClean());
          sc_ = null;
        }
        return scBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.Message)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.Message)
    private static final com.bingo.server.msg.MSG.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.MSG.Message();
    }

    public static com.bingo.server.msg.MSG.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.MSG.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\003MSG\022\024com.bingo.server.msg\032\003REQ\032\004RESP\032\006" +
      "NOTIFY\032\023ClientMessage.proto\032\023ServerMessa" +
      "ge.proto\"\263\002\n\007Message\022.\n\007msgCode\030\001 \001(\0162\035." +
      "com.bingo.server.msg.MsgCode\022\020\n\010sequence" +
      "\030\002 \001(\006\022.\n\007request\030\004 \001(\0132\035.com.bingo.serv" +
      "er.msg.Request\0220\n\010response\030\005 \001(\0132\036.com.b" +
      "ingo.server.msg.Response\0228\n\014notification" +
      "\030\006 \001(\0132\".com.bingo.server.msg.Notificati" +
      "on\022$\n\002cs\030\007 \001(\0132\030.com.bingo.server.msg.CS" +
      "\022$\n\002sc\030\010 \001(\0132\030.com.bingo.server.msg.SC*\217",
      "\r\n\007MsgCode\022\022\n\016No_Support_Msg\020\000\022\026\n\022Heart_" +
      "Beat_Request\020\001\022\027\n\023Heart_Beat_Response\020\002\022" +
      "\031\n\024Weixin_Login_Request\020\235N\022\025\n\020Registry_R" +
      "equest\020\233N\022\022\n\rLogin_Request\020\221N\022\023\n\016Logout_" +
      "Request\020\223N\022\034\n\027Lastest_Version_Request\020\244N" +
      "\022\026\n\021Timestamp_Request\020\246N\022\032\n\025Get_User_Inf" +
      "o_Request\020\250N\022\036\n\031Get_Validate_Code_Reques" +
      "t\020\252N\022\027\n\022Bind_Phone_Request\020\253N\022\032\n\025Get_Bro" +
      "adcast_Request\020\255N\022\030\n\023Get_Message_Request" +
      "\020\257N\022\032\n\024Ddz_Get_Rule_Request\020\271\216\003\022\032\n\024Ddz_N",
      "ew_Desk_Request\020\321\206\003\022\037\n\031Ddz_Check_In_Desk" +
      "_Request\020\327\206\003\022\036\n\030Ddz_Confirm_Rule_Request" +
      "\020\325\206\003\022\031\n\023Get_Friends_Request\020\331\206\003\022\030\n\022Enter" +
      "_Desk_Request\020\333\206\003\022\034\n\026Reconnect_Desk_Requ" +
      "est\020\335\206\003\022\027\n\021Ddz_Ready_Request\020\337\206\003\022\033\n\025Ddz_" +
      "Call_Lord_Request\020\341\206\003\022\033\n\025Ddz_Play_Card_R" +
      "equest\020\342\206\003\022\024\n\020Success_Response\020\n\022\032\n\025Weix" +
      "in_Login_Response\020\236N\022\026\n\021Registry_Respons" +
      "e\020\234N\022\023\n\016Login_Response\020\222N\022\024\n\017Logout_Resp" +
      "onse\020\224N\022\035\n\030Lastest_Version_Response\020\245N\022\027",
      "\n\022Timestamp_Response\020\247N\022\033\n\026Get_User_Info" +
      "_Response\020\251N\022\030\n\023Bind_Phone_Response\020\254N\022\033" +
      "\n\026Get_Broadcast_Response\020\256N\022\031\n\024Get_Messa" +
      "ge_Response\020\260N\022\033\n\025Ddz_Get_Rule_Response\020" +
      "\361\206\003\022 \n\032Ddz_Check_In_Desk_Response\020\330\206\003\022\037\n" +
      "\031Ddz_Confirm_Rule_Response\020\326\206\003\022\032\n\024Get_Fr" +
      "iends_Response\020\332\206\003\022\031\n\023Enter_Desk_Respons" +
      "e\020\334\206\003\022\035\n\027Reconnect_Desk_Response\020\336\206\003\022\030\n\022" +
      "Ddz_Ready_Response\020\340\206\003\022\033\n\027On_Connect_Not" +
      "ification\020\013\022\037\n\031Ddz_New_Desk_Notification",
      "\020\322\206\003\022!\n\033Ddz_Enter_Desk_Notification\020\323\206\003\022" +
      "\034\n\026Ddz_Error_Notification\020\324\206\003\022\"\n\034Ddz_Des" +
      "k_Status_Notification\020\344\206\003\022\033\n\025Ddz_User_No" +
      "tification\020\345\206\003\022 \n\032Ddz_Play_Card_Notifica" +
      "tion\020\343\206\003\022\021\n\014SYSTEM_ERROR\020\217N\022\023\n\016BUSINESS_" +
      "ERROR\020\216N\022\025\n\020NOT_ONLINE_ERROR\020\215N\022\026\n\021NOT_C" +
      "ONNECT_ERROR\020\214N\022\032\n\025ACCOUNT_DISABLE_ERROR" +
      "\020\213N\022\025\n\020NO_VERSION_ERROR\020\212N\022\031\n\024USER_NOT_E" +
      "XIST_ERROR\020\211N\022\033\n\026WALLET_NOT_EXIST_ERROR\020" +
      "\210N\022\036\n\031PHONE_CODE_VALIDATE_ERROR\020\207N\022\026\n\020DD",
      "Z_SYSTEM_ERROR\020\203\262\003\022\030\n\022DDZ_BUSINESS_ERROR" +
      "\020\202\262\003\022\020\n\013Landlord_CS\020\361.\022\020\n\013Landlord_SC\020\362." +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bingo.server.msg.REQ.getDescriptor(),
          com.bingo.server.msg.RESP.getDescriptor(),
          com.bingo.server.msg.NOTIFY.getDescriptor(),
          com.bingo.server.msg.ClientMessage.getDescriptor(),
          com.bingo.server.msg.ServerMessage.getDescriptor(),
        }, assigner);
    internal_static_com_bingo_server_msg_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bingo_server_msg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_Message_descriptor,
        new java.lang.String[] { "MsgCode", "Sequence", "Request", "Response", "Notification", "Cs", "Sc", });
    com.bingo.server.msg.REQ.getDescriptor();
    com.bingo.server.msg.RESP.getDescriptor();
    com.bingo.server.msg.NOTIFY.getDescriptor();
    com.bingo.server.msg.ClientMessage.getDescriptor();
    com.bingo.server.msg.ServerMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
