// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Role.proto

package com.bingo.server.msg;

public final class Role {
  private Role() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoleRenameRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.RoleRenameRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.RoleRenameRequest}
   */
  public  static final class RoleRenameRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.RoleRenameRequest)
      RoleRenameRequestOrBuilder {
    // Use RoleRenameRequest.newBuilder() to construct.
    private RoleRenameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleRenameRequest() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoleRenameRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Role.RoleRenameRequest.class, com.bingo.server.msg.Role.RoleRenameRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Role.RoleRenameRequest)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Role.RoleRenameRequest other = (com.bingo.server.msg.Role.RoleRenameRequest) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.RoleRenameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Role.RoleRenameRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.RoleRenameRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.RoleRenameRequest)
        com.bingo.server.msg.Role.RoleRenameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Role.RoleRenameRequest.class, com.bingo.server.msg.Role.RoleRenameRequest.Builder.class);
      }

      // Construct using com.bingo.server.msg.Role.RoleRenameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameRequest_descriptor;
      }

      public com.bingo.server.msg.Role.RoleRenameRequest getDefaultInstanceForType() {
        return com.bingo.server.msg.Role.RoleRenameRequest.getDefaultInstance();
      }

      public com.bingo.server.msg.Role.RoleRenameRequest build() {
        com.bingo.server.msg.Role.RoleRenameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Role.RoleRenameRequest buildPartial() {
        com.bingo.server.msg.Role.RoleRenameRequest result = new com.bingo.server.msg.Role.RoleRenameRequest(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Role.RoleRenameRequest) {
          return mergeFrom((com.bingo.server.msg.Role.RoleRenameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Role.RoleRenameRequest other) {
        if (other == com.bingo.server.msg.Role.RoleRenameRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Role.RoleRenameRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Role.RoleRenameRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.RoleRenameRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.RoleRenameRequest)
    private static final com.bingo.server.msg.Role.RoleRenameRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Role.RoleRenameRequest();
    }

    public static com.bingo.server.msg.Role.RoleRenameRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleRenameRequest>
        PARSER = new com.google.protobuf.AbstractParser<RoleRenameRequest>() {
      public RoleRenameRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoleRenameRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleRenameRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleRenameRequest> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Role.RoleRenameRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoleRenameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.RoleRenameResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.RoleRenameResponse}
   */
  public  static final class RoleRenameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.RoleRenameResponse)
      RoleRenameResponseOrBuilder {
    // Use RoleRenameResponse.newBuilder() to construct.
    private RoleRenameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleRenameResponse() {
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoleRenameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Role.RoleRenameResponse.class, com.bingo.server.msg.Role.RoleRenameResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Role.RoleRenameResponse)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Role.RoleRenameResponse other = (com.bingo.server.msg.Role.RoleRenameResponse) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.RoleRenameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Role.RoleRenameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.RoleRenameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.RoleRenameResponse)
        com.bingo.server.msg.Role.RoleRenameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Role.RoleRenameResponse.class, com.bingo.server.msg.Role.RoleRenameResponse.Builder.class);
      }

      // Construct using com.bingo.server.msg.Role.RoleRenameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_RoleRenameResponse_descriptor;
      }

      public com.bingo.server.msg.Role.RoleRenameResponse getDefaultInstanceForType() {
        return com.bingo.server.msg.Role.RoleRenameResponse.getDefaultInstance();
      }

      public com.bingo.server.msg.Role.RoleRenameResponse build() {
        com.bingo.server.msg.Role.RoleRenameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Role.RoleRenameResponse buildPartial() {
        com.bingo.server.msg.Role.RoleRenameResponse result = new com.bingo.server.msg.Role.RoleRenameResponse(this);
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Role.RoleRenameResponse) {
          return mergeFrom((com.bingo.server.msg.Role.RoleRenameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Role.RoleRenameResponse other) {
        if (other == com.bingo.server.msg.Role.RoleRenameResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Role.RoleRenameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Role.RoleRenameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.RoleRenameResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.RoleRenameResponse)
    private static final com.bingo.server.msg.Role.RoleRenameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Role.RoleRenameResponse();
    }

    public static com.bingo.server.msg.Role.RoleRenameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleRenameResponse>
        PARSER = new com.google.protobuf.AbstractParser<RoleRenameResponse>() {
      public RoleRenameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoleRenameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleRenameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleRenameResponse> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Role.RoleRenameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRoleDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.GetRoleDataRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.GetRoleDataRequest}
   */
  public  static final class GetRoleDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.GetRoleDataRequest)
      GetRoleDataRequestOrBuilder {
    // Use GetRoleDataRequest.newBuilder() to construct.
    private GetRoleDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRoleDataRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetRoleDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Role.GetRoleDataRequest.class, com.bingo.server.msg.Role.GetRoleDataRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Role.GetRoleDataRequest)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Role.GetRoleDataRequest other = (com.bingo.server.msg.Role.GetRoleDataRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.GetRoleDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Role.GetRoleDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.GetRoleDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.GetRoleDataRequest)
        com.bingo.server.msg.Role.GetRoleDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Role.GetRoleDataRequest.class, com.bingo.server.msg.Role.GetRoleDataRequest.Builder.class);
      }

      // Construct using com.bingo.server.msg.Role.GetRoleDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataRequest_descriptor;
      }

      public com.bingo.server.msg.Role.GetRoleDataRequest getDefaultInstanceForType() {
        return com.bingo.server.msg.Role.GetRoleDataRequest.getDefaultInstance();
      }

      public com.bingo.server.msg.Role.GetRoleDataRequest build() {
        com.bingo.server.msg.Role.GetRoleDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Role.GetRoleDataRequest buildPartial() {
        com.bingo.server.msg.Role.GetRoleDataRequest result = new com.bingo.server.msg.Role.GetRoleDataRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Role.GetRoleDataRequest) {
          return mergeFrom((com.bingo.server.msg.Role.GetRoleDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Role.GetRoleDataRequest other) {
        if (other == com.bingo.server.msg.Role.GetRoleDataRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Role.GetRoleDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Role.GetRoleDataRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.GetRoleDataRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.GetRoleDataRequest)
    private static final com.bingo.server.msg.Role.GetRoleDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Role.GetRoleDataRequest();
    }

    public static com.bingo.server.msg.Role.GetRoleDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRoleDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetRoleDataRequest>() {
      public GetRoleDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetRoleDataRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRoleDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRoleDataRequest> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Role.GetRoleDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRoleDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.GetRoleDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    int getErrorCode();

    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    boolean hasRoleData();
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    com.bingo.server.msg.Entity.RoleData getRoleData();
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    com.bingo.server.msg.Entity.RoleDataOrBuilder getRoleDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.GetRoleDataResponse}
   */
  public  static final class GetRoleDataResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.GetRoleDataResponse)
      GetRoleDataResponseOrBuilder {
    // Use GetRoleDataResponse.newBuilder() to construct.
    private GetRoleDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRoleDataResponse() {
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetRoleDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.bingo.server.msg.Entity.RoleData.Builder subBuilder = null;
              if (roleData_ != null) {
                subBuilder = roleData_.toBuilder();
              }
              roleData_ = input.readMessage(com.bingo.server.msg.Entity.RoleData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(roleData_);
                roleData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Role.GetRoleDataResponse.class, com.bingo.server.msg.Role.GetRoleDataResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ROLEDATA_FIELD_NUMBER = 2;
    private com.bingo.server.msg.Entity.RoleData roleData_;
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    public boolean hasRoleData() {
      return roleData_ != null;
    }
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    public com.bingo.server.msg.Entity.RoleData getRoleData() {
      return roleData_ == null ? com.bingo.server.msg.Entity.RoleData.getDefaultInstance() : roleData_;
    }
    /**
     * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
     */
    public com.bingo.server.msg.Entity.RoleDataOrBuilder getRoleDataOrBuilder() {
      return getRoleData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      if (roleData_ != null) {
        output.writeMessage(2, getRoleData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (roleData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRoleData());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Role.GetRoleDataResponse)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Role.GetRoleDataResponse other = (com.bingo.server.msg.Role.GetRoleDataResponse) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && (hasRoleData() == other.hasRoleData());
      if (hasRoleData()) {
        result = result && getRoleData()
            .equals(other.getRoleData());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      if (hasRoleData()) {
        hash = (37 * hash) + ROLEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getRoleData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Role.GetRoleDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Role.GetRoleDataResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.GetRoleDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.GetRoleDataResponse)
        com.bingo.server.msg.Role.GetRoleDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Role.GetRoleDataResponse.class, com.bingo.server.msg.Role.GetRoleDataResponse.Builder.class);
      }

      // Construct using com.bingo.server.msg.Role.GetRoleDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        if (roleDataBuilder_ == null) {
          roleData_ = null;
        } else {
          roleData_ = null;
          roleDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Role.internal_static_com_bingo_server_msg_GetRoleDataResponse_descriptor;
      }

      public com.bingo.server.msg.Role.GetRoleDataResponse getDefaultInstanceForType() {
        return com.bingo.server.msg.Role.GetRoleDataResponse.getDefaultInstance();
      }

      public com.bingo.server.msg.Role.GetRoleDataResponse build() {
        com.bingo.server.msg.Role.GetRoleDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Role.GetRoleDataResponse buildPartial() {
        com.bingo.server.msg.Role.GetRoleDataResponse result = new com.bingo.server.msg.Role.GetRoleDataResponse(this);
        result.errorCode_ = errorCode_;
        if (roleDataBuilder_ == null) {
          result.roleData_ = roleData_;
        } else {
          result.roleData_ = roleDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Role.GetRoleDataResponse) {
          return mergeFrom((com.bingo.server.msg.Role.GetRoleDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Role.GetRoleDataResponse other) {
        if (other == com.bingo.server.msg.Role.GetRoleDataResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasRoleData()) {
          mergeRoleData(other.getRoleData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Role.GetRoleDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Role.GetRoleDataResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.bingo.server.msg.Entity.RoleData roleData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.Entity.RoleData, com.bingo.server.msg.Entity.RoleData.Builder, com.bingo.server.msg.Entity.RoleDataOrBuilder> roleDataBuilder_;
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public boolean hasRoleData() {
        return roleDataBuilder_ != null || roleData_ != null;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public com.bingo.server.msg.Entity.RoleData getRoleData() {
        if (roleDataBuilder_ == null) {
          return roleData_ == null ? com.bingo.server.msg.Entity.RoleData.getDefaultInstance() : roleData_;
        } else {
          return roleDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder setRoleData(com.bingo.server.msg.Entity.RoleData value) {
        if (roleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          roleData_ = value;
          onChanged();
        } else {
          roleDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder setRoleData(
          com.bingo.server.msg.Entity.RoleData.Builder builderForValue) {
        if (roleDataBuilder_ == null) {
          roleData_ = builderForValue.build();
          onChanged();
        } else {
          roleDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder mergeRoleData(com.bingo.server.msg.Entity.RoleData value) {
        if (roleDataBuilder_ == null) {
          if (roleData_ != null) {
            roleData_ =
              com.bingo.server.msg.Entity.RoleData.newBuilder(roleData_).mergeFrom(value).buildPartial();
          } else {
            roleData_ = value;
          }
          onChanged();
        } else {
          roleDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public Builder clearRoleData() {
        if (roleDataBuilder_ == null) {
          roleData_ = null;
          onChanged();
        } else {
          roleData_ = null;
          roleDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public com.bingo.server.msg.Entity.RoleData.Builder getRoleDataBuilder() {
        
        onChanged();
        return getRoleDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      public com.bingo.server.msg.Entity.RoleDataOrBuilder getRoleDataOrBuilder() {
        if (roleDataBuilder_ != null) {
          return roleDataBuilder_.getMessageOrBuilder();
        } else {
          return roleData_ == null ?
              com.bingo.server.msg.Entity.RoleData.getDefaultInstance() : roleData_;
        }
      }
      /**
       * <code>optional .com.bingo.server.msg.RoleData roleData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bingo.server.msg.Entity.RoleData, com.bingo.server.msg.Entity.RoleData.Builder, com.bingo.server.msg.Entity.RoleDataOrBuilder> 
          getRoleDataFieldBuilder() {
        if (roleDataBuilder_ == null) {
          roleDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bingo.server.msg.Entity.RoleData, com.bingo.server.msg.Entity.RoleData.Builder, com.bingo.server.msg.Entity.RoleDataOrBuilder>(
                  getRoleData(),
                  getParentForChildren(),
                  isClean());
          roleData_ = null;
        }
        return roleDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.GetRoleDataResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.GetRoleDataResponse)
    private static final com.bingo.server.msg.Role.GetRoleDataResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Role.GetRoleDataResponse();
    }

    public static com.bingo.server.msg.Role.GetRoleDataResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRoleDataResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetRoleDataResponse>() {
      public GetRoleDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetRoleDataResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRoleDataResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRoleDataResponse> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Role.GetRoleDataResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_RoleRenameRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_RoleRenameRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_RoleRenameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_RoleRenameResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_GetRoleDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_GetRoleDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_GetRoleDataResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_GetRoleDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRole.proto\022\024com.bingo.server.msg\032\014Enti" +
      "ty.proto\"!\n\021RoleRenameRequest\022\014\n\004name\030\001 " +
      "\001(\t\"\'\n\022RoleRenameResponse\022\021\n\terrorCode\030\001" +
      " \001(\005\"\024\n\022GetRoleDataRequest\"Z\n\023GetRoleDat" +
      "aResponse\022\021\n\terrorCode\030\001 \001(\005\0220\n\010roleData" +
      "\030\002 \001(\0132\036.com.bingo.server.msg.RoleDatab\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bingo.server.msg.Entity.getDescriptor(),
        }, assigner);
    internal_static_com_bingo_server_msg_RoleRenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bingo_server_msg_RoleRenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_RoleRenameRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bingo_server_msg_RoleRenameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bingo_server_msg_RoleRenameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_RoleRenameResponse_descriptor,
        new java.lang.String[] { "ErrorCode", });
    internal_static_com_bingo_server_msg_GetRoleDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bingo_server_msg_GetRoleDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_GetRoleDataRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_bingo_server_msg_GetRoleDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bingo_server_msg_GetRoleDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_GetRoleDataResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "RoleData", });
    com.bingo.server.msg.Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
