// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Settings.proto

package com.bingo.server.msg;

public final class Settings {
  private Settings() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SettingsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.SettingsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 volume = 1;</code>
     */
    int getVolume();

    /**
     * <code>optional int32 musicVolume = 2;</code>
     */
    int getMusicVolume();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.SettingsRequest}
   */
  public  static final class SettingsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.SettingsRequest)
      SettingsRequestOrBuilder {
    // Use SettingsRequest.newBuilder() to construct.
    private SettingsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SettingsRequest() {
      volume_ = 0;
      musicVolume_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SettingsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              volume_ = input.readInt32();
              break;
            }
            case 16: {

              musicVolume_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Settings.SettingsRequest.class, com.bingo.server.msg.Settings.SettingsRequest.Builder.class);
    }

    public static final int VOLUME_FIELD_NUMBER = 1;
    private int volume_;
    /**
     * <code>optional int32 volume = 1;</code>
     */
    public int getVolume() {
      return volume_;
    }

    public static final int MUSICVOLUME_FIELD_NUMBER = 2;
    private int musicVolume_;
    /**
     * <code>optional int32 musicVolume = 2;</code>
     */
    public int getMusicVolume() {
      return musicVolume_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (volume_ != 0) {
        output.writeInt32(1, volume_);
      }
      if (musicVolume_ != 0) {
        output.writeInt32(2, musicVolume_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (volume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, volume_);
      }
      if (musicVolume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, musicVolume_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Settings.SettingsRequest)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Settings.SettingsRequest other = (com.bingo.server.msg.Settings.SettingsRequest) obj;

      boolean result = true;
      result = result && (getVolume()
          == other.getVolume());
      result = result && (getMusicVolume()
          == other.getMusicVolume());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getVolume();
      hash = (37 * hash) + MUSICVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getMusicVolume();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.SettingsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Settings.SettingsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.SettingsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.SettingsRequest)
        com.bingo.server.msg.Settings.SettingsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Settings.SettingsRequest.class, com.bingo.server.msg.Settings.SettingsRequest.Builder.class);
      }

      // Construct using com.bingo.server.msg.Settings.SettingsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        volume_ = 0;

        musicVolume_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsRequest_descriptor;
      }

      public com.bingo.server.msg.Settings.SettingsRequest getDefaultInstanceForType() {
        return com.bingo.server.msg.Settings.SettingsRequest.getDefaultInstance();
      }

      public com.bingo.server.msg.Settings.SettingsRequest build() {
        com.bingo.server.msg.Settings.SettingsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Settings.SettingsRequest buildPartial() {
        com.bingo.server.msg.Settings.SettingsRequest result = new com.bingo.server.msg.Settings.SettingsRequest(this);
        result.volume_ = volume_;
        result.musicVolume_ = musicVolume_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Settings.SettingsRequest) {
          return mergeFrom((com.bingo.server.msg.Settings.SettingsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Settings.SettingsRequest other) {
        if (other == com.bingo.server.msg.Settings.SettingsRequest.getDefaultInstance()) return this;
        if (other.getVolume() != 0) {
          setVolume(other.getVolume());
        }
        if (other.getMusicVolume() != 0) {
          setMusicVolume(other.getMusicVolume());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Settings.SettingsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Settings.SettingsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int volume_ ;
      /**
       * <code>optional int32 volume = 1;</code>
       */
      public int getVolume() {
        return volume_;
      }
      /**
       * <code>optional int32 volume = 1;</code>
       */
      public Builder setVolume(int value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 volume = 1;</code>
       */
      public Builder clearVolume() {
        
        volume_ = 0;
        onChanged();
        return this;
      }

      private int musicVolume_ ;
      /**
       * <code>optional int32 musicVolume = 2;</code>
       */
      public int getMusicVolume() {
        return musicVolume_;
      }
      /**
       * <code>optional int32 musicVolume = 2;</code>
       */
      public Builder setMusicVolume(int value) {
        
        musicVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 musicVolume = 2;</code>
       */
      public Builder clearMusicVolume() {
        
        musicVolume_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.SettingsRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.SettingsRequest)
    private static final com.bingo.server.msg.Settings.SettingsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Settings.SettingsRequest();
    }

    public static com.bingo.server.msg.Settings.SettingsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SettingsRequest>
        PARSER = new com.google.protobuf.AbstractParser<SettingsRequest>() {
      public SettingsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SettingsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SettingsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SettingsRequest> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Settings.SettingsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SettingsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.SettingsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.SettingsResponse}
   */
  public  static final class SettingsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.SettingsResponse)
      SettingsResponseOrBuilder {
    // Use SettingsResponse.newBuilder() to construct.
    private SettingsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SettingsResponse() {
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SettingsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Settings.SettingsResponse.class, com.bingo.server.msg.Settings.SettingsResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Settings.SettingsResponse)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Settings.SettingsResponse other = (com.bingo.server.msg.Settings.SettingsResponse) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.SettingsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Settings.SettingsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.SettingsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.SettingsResponse)
        com.bingo.server.msg.Settings.SettingsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Settings.SettingsResponse.class, com.bingo.server.msg.Settings.SettingsResponse.Builder.class);
      }

      // Construct using com.bingo.server.msg.Settings.SettingsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_SettingsResponse_descriptor;
      }

      public com.bingo.server.msg.Settings.SettingsResponse getDefaultInstanceForType() {
        return com.bingo.server.msg.Settings.SettingsResponse.getDefaultInstance();
      }

      public com.bingo.server.msg.Settings.SettingsResponse build() {
        com.bingo.server.msg.Settings.SettingsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Settings.SettingsResponse buildPartial() {
        com.bingo.server.msg.Settings.SettingsResponse result = new com.bingo.server.msg.Settings.SettingsResponse(this);
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Settings.SettingsResponse) {
          return mergeFrom((com.bingo.server.msg.Settings.SettingsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Settings.SettingsResponse other) {
        if (other == com.bingo.server.msg.Settings.SettingsResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Settings.SettingsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Settings.SettingsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.SettingsResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.SettingsResponse)
    private static final com.bingo.server.msg.Settings.SettingsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Settings.SettingsResponse();
    }

    public static com.bingo.server.msg.Settings.SettingsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SettingsResponse>
        PARSER = new com.google.protobuf.AbstractParser<SettingsResponse>() {
      public SettingsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SettingsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SettingsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SettingsResponse> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Settings.SettingsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSettingsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.GetSettingsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.GetSettingsRequest}
   */
  public  static final class GetSettingsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.GetSettingsRequest)
      GetSettingsRequestOrBuilder {
    // Use GetSettingsRequest.newBuilder() to construct.
    private GetSettingsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSettingsRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetSettingsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Settings.GetSettingsRequest.class, com.bingo.server.msg.Settings.GetSettingsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Settings.GetSettingsRequest)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Settings.GetSettingsRequest other = (com.bingo.server.msg.Settings.GetSettingsRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.GetSettingsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Settings.GetSettingsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.GetSettingsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.GetSettingsRequest)
        com.bingo.server.msg.Settings.GetSettingsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Settings.GetSettingsRequest.class, com.bingo.server.msg.Settings.GetSettingsRequest.Builder.class);
      }

      // Construct using com.bingo.server.msg.Settings.GetSettingsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsRequest_descriptor;
      }

      public com.bingo.server.msg.Settings.GetSettingsRequest getDefaultInstanceForType() {
        return com.bingo.server.msg.Settings.GetSettingsRequest.getDefaultInstance();
      }

      public com.bingo.server.msg.Settings.GetSettingsRequest build() {
        com.bingo.server.msg.Settings.GetSettingsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Settings.GetSettingsRequest buildPartial() {
        com.bingo.server.msg.Settings.GetSettingsRequest result = new com.bingo.server.msg.Settings.GetSettingsRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Settings.GetSettingsRequest) {
          return mergeFrom((com.bingo.server.msg.Settings.GetSettingsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Settings.GetSettingsRequest other) {
        if (other == com.bingo.server.msg.Settings.GetSettingsRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Settings.GetSettingsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Settings.GetSettingsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.GetSettingsRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.GetSettingsRequest)
    private static final com.bingo.server.msg.Settings.GetSettingsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Settings.GetSettingsRequest();
    }

    public static com.bingo.server.msg.Settings.GetSettingsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSettingsRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetSettingsRequest>() {
      public GetSettingsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSettingsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSettingsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSettingsRequest> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Settings.GetSettingsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSettingsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bingo.server.msg.GetSettingsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    int getErrorCode();

    /**
     * <code>optional int32 volume = 2;</code>
     */
    int getVolume();

    /**
     * <code>optional int32 musicVolume = 3;</code>
     */
    int getMusicVolume();
  }
  /**
   * Protobuf type {@code com.bingo.server.msg.GetSettingsResponse}
   */
  public  static final class GetSettingsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bingo.server.msg.GetSettingsResponse)
      GetSettingsResponseOrBuilder {
    // Use GetSettingsResponse.newBuilder() to construct.
    private GetSettingsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSettingsResponse() {
      errorCode_ = 0;
      volume_ = 0;
      musicVolume_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetSettingsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 16: {

              volume_ = input.readInt32();
              break;
            }
            case 24: {

              musicVolume_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bingo.server.msg.Settings.GetSettingsResponse.class, com.bingo.server.msg.Settings.GetSettingsResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int VOLUME_FIELD_NUMBER = 2;
    private int volume_;
    /**
     * <code>optional int32 volume = 2;</code>
     */
    public int getVolume() {
      return volume_;
    }

    public static final int MUSICVOLUME_FIELD_NUMBER = 3;
    private int musicVolume_;
    /**
     * <code>optional int32 musicVolume = 3;</code>
     */
    public int getMusicVolume() {
      return musicVolume_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      if (volume_ != 0) {
        output.writeInt32(2, volume_);
      }
      if (musicVolume_ != 0) {
        output.writeInt32(3, musicVolume_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (volume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, volume_);
      }
      if (musicVolume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, musicVolume_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bingo.server.msg.Settings.GetSettingsResponse)) {
        return super.equals(obj);
      }
      com.bingo.server.msg.Settings.GetSettingsResponse other = (com.bingo.server.msg.Settings.GetSettingsResponse) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && (getVolume()
          == other.getVolume());
      result = result && (getMusicVolume()
          == other.getMusicVolume());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getVolume();
      hash = (37 * hash) + MUSICVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getMusicVolume();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bingo.server.msg.Settings.GetSettingsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bingo.server.msg.Settings.GetSettingsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bingo.server.msg.GetSettingsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bingo.server.msg.GetSettingsResponse)
        com.bingo.server.msg.Settings.GetSettingsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bingo.server.msg.Settings.GetSettingsResponse.class, com.bingo.server.msg.Settings.GetSettingsResponse.Builder.class);
      }

      // Construct using com.bingo.server.msg.Settings.GetSettingsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        volume_ = 0;

        musicVolume_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bingo.server.msg.Settings.internal_static_com_bingo_server_msg_GetSettingsResponse_descriptor;
      }

      public com.bingo.server.msg.Settings.GetSettingsResponse getDefaultInstanceForType() {
        return com.bingo.server.msg.Settings.GetSettingsResponse.getDefaultInstance();
      }

      public com.bingo.server.msg.Settings.GetSettingsResponse build() {
        com.bingo.server.msg.Settings.GetSettingsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bingo.server.msg.Settings.GetSettingsResponse buildPartial() {
        com.bingo.server.msg.Settings.GetSettingsResponse result = new com.bingo.server.msg.Settings.GetSettingsResponse(this);
        result.errorCode_ = errorCode_;
        result.volume_ = volume_;
        result.musicVolume_ = musicVolume_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bingo.server.msg.Settings.GetSettingsResponse) {
          return mergeFrom((com.bingo.server.msg.Settings.GetSettingsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bingo.server.msg.Settings.GetSettingsResponse other) {
        if (other == com.bingo.server.msg.Settings.GetSettingsResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.getVolume() != 0) {
          setVolume(other.getVolume());
        }
        if (other.getMusicVolume() != 0) {
          setMusicVolume(other.getMusicVolume());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bingo.server.msg.Settings.GetSettingsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bingo.server.msg.Settings.GetSettingsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private int volume_ ;
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public int getVolume() {
        return volume_;
      }
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public Builder setVolume(int value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public Builder clearVolume() {
        
        volume_ = 0;
        onChanged();
        return this;
      }

      private int musicVolume_ ;
      /**
       * <code>optional int32 musicVolume = 3;</code>
       */
      public int getMusicVolume() {
        return musicVolume_;
      }
      /**
       * <code>optional int32 musicVolume = 3;</code>
       */
      public Builder setMusicVolume(int value) {
        
        musicVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 musicVolume = 3;</code>
       */
      public Builder clearMusicVolume() {
        
        musicVolume_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.bingo.server.msg.GetSettingsResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bingo.server.msg.GetSettingsResponse)
    private static final com.bingo.server.msg.Settings.GetSettingsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bingo.server.msg.Settings.GetSettingsResponse();
    }

    public static com.bingo.server.msg.Settings.GetSettingsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSettingsResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetSettingsResponse>() {
      public GetSettingsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSettingsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSettingsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSettingsResponse> getParserForType() {
      return PARSER;
    }

    public com.bingo.server.msg.Settings.GetSettingsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_SettingsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_SettingsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_SettingsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_SettingsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_GetSettingsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_GetSettingsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bingo_server_msg_GetSettingsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bingo_server_msg_GetSettingsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Settings.proto\022\024com.bingo.server.msg\"6" +
      "\n\017SettingsRequest\022\016\n\006volume\030\001 \001(\005\022\023\n\013mus" +
      "icVolume\030\002 \001(\005\"%\n\020SettingsResponse\022\021\n\ter" +
      "rorCode\030\001 \001(\005\"\024\n\022GetSettingsRequest\"M\n\023G" +
      "etSettingsResponse\022\021\n\terrorCode\030\001 \001(\005\022\016\n" +
      "\006volume\030\002 \001(\005\022\023\n\013musicVolume\030\003 \001(\005b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bingo_server_msg_SettingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bingo_server_msg_SettingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_SettingsRequest_descriptor,
        new java.lang.String[] { "Volume", "MusicVolume", });
    internal_static_com_bingo_server_msg_SettingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bingo_server_msg_SettingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_SettingsResponse_descriptor,
        new java.lang.String[] { "ErrorCode", });
    internal_static_com_bingo_server_msg_GetSettingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bingo_server_msg_GetSettingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_GetSettingsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_bingo_server_msg_GetSettingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bingo_server_msg_GetSettingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bingo_server_msg_GetSettingsResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "Volume", "MusicVolume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
